/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ThaoTacNV;
import controller.ThaoTacPC;
import controller.ThaoTacSP;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cong;
import model.CongNhan;
import model.SanPham;

/**
 *
 * @author ADMIN
 */
public class ViewHome extends javax.swing.JFrame {

    private List<CongNhan> listCN;
    private List<SanPham> listSP;
    private List<Cong> ListPC;
    private Vector<String> vcMaCN = new Vector<>(), vcTenCN = new Vector<>(),
            vcTenSP = new Vector<>(), vcSoLuong = new Vector<>(), vcDonGia = new Vector<>();

    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        initComponents();
        readCN();
        viewTableCN();
        readListSP();
        viewTableSP();
        ListPC = ThaoTacPC.readFile();
        phanTach();
        viewTablePC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCN = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tenNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        diaChiNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caSX = new javax.swing.JComboBox<>();
        themNV = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSP = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tenSP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        donGia = new javax.swing.JTextField();
        themSP = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePC = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        maCN2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maSP2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        soluong = new javax.swing.JTextField();
        themPC = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        xacNhan = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableThuNhap = new javax.swing.JTable();
        lamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jTableCN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma nhan vien", "Ten nhan vien", "Dia chi", "Ca lam viec"
            }
        ));
        jScrollPane1.setViewportView(jTableCN);

        jLabel1.setText("Ten nhan vien:");

        jLabel2.setText("Dia chi: ");

        jLabel3.setText("Ca SX:");

        caSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca sang", "Ca chieu", "Ca dem" }));

        themNV.setText("Them");
        themNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenNV)
                            .addComponent(diaChiNV)
                            .addComponent(caSX, 0, 224, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themNV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(diaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("Nhan vien", jToolBar1);

        jToolBar2.setRollover(true);

        jTableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma SP", "Ten", "Don gia"
            }
        ));
        jScrollPane2.setViewportView(jTableSP);

        jLabel4.setText("Ten san pham:");

        jLabel5.setText("Don gia:");

        donGia.setText("0");

        themSP.setText("Them");
        themSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenSP)
                            .addComponent(donGia, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themSP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel2);

        jTabbedPane1.addTab("San pham", jToolBar2);

        jToolBar3.setRollover(true);

        jTablePC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma cong nhan", "Ten cong nhan", "Ten san pham", "So luong", "Don gia"
            }
        ));
        jScrollPane3.setViewportView(jTablePC);

        jLabel6.setText("Ten/ma cong nhan:");

        jLabel7.setText("Ten/ma san pham:");

        jLabel8.setText("So luong:");

        soluong.setText("0");

        themPC.setText("Them");
        themPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themPCActionPerformed(evt);
            }
        });

        jLabel10.setText("Sap xep theo:");

        xacNhan.setText("Xac nhan");
        xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhanActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ho ten cong nhan", "So luong san pham" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maCN2)
                            .addComponent(maSP2)
                            .addComponent(soluong, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themPC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xacNhan)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maCN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(maSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themPC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(xacNhan)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jToolBar3.add(jPanel3);

        jTabbedPane1.addTab("Phan cong", jToolBar3);

        jToolBar4.setRollover(true);

        jTableThuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma nhan vien", "Ten nhan vien", "Thu nhap"
            }
        ));
        jScrollPane4.setViewportView(jTableThuNhap);

        lamMoi.setText("Lam moi");
        lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lamMoi)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lamMoi)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jToolBar4.add(jPanel4);

        jTabbedPane1.addTab("Thu nhap", jToolBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNVActionPerformed
        // TODO add your handling code here:
        themCN();
    }//GEN-LAST:event_themNVActionPerformed

    private void themSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSPActionPerformed
        // TODO add your handling code here:
        themSP();
    }//GEN-LAST:event_themSPActionPerformed

    private void themPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themPCActionPerformed
        // TODO add your handling code here:
        CongNhan cn = ThaoTacNV.tim(listCN, maCN2.getText());
        SanPham sp = ThaoTacSP.tim(listSP, maSP2.getText());
        int x = Integer.parseInt(soluong.getText());
        
        if(cn != null && sp != null && x >= 0){
            
            Cong cong = ThaoTacPC.kiemTra(ListPC, cn);
            if(cong != null){
                
                if(!cong.themSanPham(sp, x))JOptionPane.showMessageDialog(rootPane, "nhan vien co toi da loai san pham");
                
            }
            else{
                cong = new Cong();
                cong.themCongNhan(cn, sp, x);
                ListPC.add(cong);
            }
            
            
            ThaoTacPC.writeFile(ListPC);
            phanTach();
            viewTablePC();
        }else JOptionPane.showMessageDialog(rootPane, "thong tin nhap sai");
    }//GEN-LAST:event_themPCActionPerformed

    private void xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacNhanActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().compareTo("Ho ten cong nhan") == 0){
            ThaoTacPC.SXTheoTen(vcMaCN, vcTenCN, vcTenSP, vcSoLuong, vcDonGia);
            viewTablePC();
        }else{
            ThaoTacPC.SXTheoSoLuong(vcMaCN, vcTenCN, vcTenSP, vcSoLuong, vcDonGia);
            viewTablePC();
        }
    }//GEN-LAST:event_xacNhanActionPerformed

    private void lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamMoiActionPerformed
       double tongThu = 0;
       DefaultTableModel model = (DefaultTableModel)jTableThuNhap.getModel();
       model.setRowCount(0);
       for(int i = 0; i < ListPC.size(); i++){
           Map<SanPham, Integer> map = ListPC.get(i).getSanPham();
           tongThu = 0;
           for(Map.Entry<SanPham, Integer> entry : map.entrySet()){
               tongThu  += entry.getKey().getDonGia()*entry.getValue();
           }
           model.addRow(new Object[]{ListPC.get(i).getCongNhan().getMa()+"", ListPC.get(i).getCongNhan().getHoTen(),
           tongThu+""});
       }
    }//GEN-LAST:event_lamMoiActionPerformed

    //them mot nhan vien
    private void themCN() {
        if (!listCN.isEmpty()) {
            CongNhan.setStMa(listCN.get(listCN.size() - 1).getMa() + 1);
        }
        Pattern pattern = Pattern.compile("\\w+");
        Matcher matcher = pattern.matcher(tenNV.getText()),
                matcher1 = pattern.matcher(diaChiNV.getText());
        if (matcher.find() && matcher1.find()) {
            CongNhan cn = new CongNhan(tenNV.getText(), diaChiNV.getText(),
                    caSX.getSelectedItem().toString());
            listCN.add(cn);
            ThaoTacNV.writeFile(listCN);
            viewTableCN();
        }
    }

    //doc danh sach cong nhan
    private void readCN() {
        listCN = ThaoTacNV.readFile();
    }

    //hien thi thong tin cong nhan ra bang
    private void viewTableCN() {
        DefaultTableModel model = (DefaultTableModel) jTableCN.getModel();

        model.setRowCount(0);
        for (int i = 0; i < listCN.size(); i++) {
            model.addRow(new Object[]{"" + listCN.get(i).getMa(), listCN.get(i).getHoTen(),
                listCN.get(i).getDiaChi(), listCN.get(i).getCaSX()});
        }
    }

    //doc danh sach san pham
    private void readListSP() {
        listSP = ThaoTacSP.readFile();
    }

    //hien thi danh sach san pham
    private void viewTableSP() {
        DefaultTableModel model = (DefaultTableModel) jTableSP.getModel();

        model.setRowCount(0);

        for (int i = 0; i < listSP.size(); i++) {
            model.addRow(new Object[]{"" + listSP.get(i).getMa(), listSP.get(i).getTen(),
                "" + listSP.get(i).getDonGia()});
        }
    }

    //them mot san pham moi
    private void themSP() {
        if (!ThaoTacSP.kiemTra(listSP, tenSP.getText())) {
            if (!listSP.isEmpty()) {
                SanPham.setStMa(listSP.get(listSP.size() - 1).getMa() + 1);
            }
            double x = Double.parseDouble(donGia.getText());
            Pattern pattern = Pattern.compile("\\w+");
            Matcher matcher = pattern.matcher(tenSP.getText());
            if (ThaoTacSP.kiemTra(listSP, tenSP.getText())) {
                JOptionPane.showMessageDialog(rootPane, "ten san pham da co");
            } else {
                if (matcher.find() && x >= 0) {
                    SanPham sp = new SanPham(tenSP.getText(), x);
                    listSP.add(sp);
                    ThaoTacSP.writeFile(listSP);
                    viewTableSP();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "thongt tin nhap khong dung");
                }
            }
        }
    }
    
    //doc danh sach phan cong
    private void readFilePC(){
        ListPC = ThaoTacPC.readFile();
    }
    
    //phan tach thong tin danh sach phan cong
    private void phanTach(){
        ThaoTacPC.phanTach(ListPC, vcMaCN, vcTenCN, vcTenSP, vcSoLuong, vcDonGia);
    }
    
    //hien thi danh sach phan cong
    private void viewTablePC(){
        DefaultTableModel model = (DefaultTableModel)jTablePC.getModel();
        model.setRowCount(0);
        
        for(int i = 0; i < vcTenCN.size(); i++){
            model.addRow(new Object[]{vcMaCN.get(i), vcTenCN.get(i), vcTenSP.get(i),
                vcSoLuong.get(i), vcDonGia.get(i)});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> caSX;
    private javax.swing.JTextField diaChiNV;
    private javax.swing.JTextField donGia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCN;
    private javax.swing.JTable jTablePC;
    private javax.swing.JTable jTableSP;
    private javax.swing.JTable jTableThuNhap;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JButton lamMoi;
    private javax.swing.JTextField maCN2;
    private javax.swing.JTextField maSP2;
    private javax.swing.JTextField soluong;
    private javax.swing.JTextField tenNV;
    private javax.swing.JTextField tenSP;
    private javax.swing.JButton themNV;
    private javax.swing.JButton themPC;
    private javax.swing.JButton themSP;
    private javax.swing.JButton xacNhan;
    // End of variables declaration//GEN-END:variables
}
