/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ThaoTacDV;
import controller.ThaoTacHD;
import controller.ThaoTacKH;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.HoaDon;
import model.KhachHang;

/**
 *
 * @author ADMIN
 */
public class ViewHome extends javax.swing.JFrame {
    private List<KhachHang> listKH;
    private List<DichVu> listDV;
    private List<HoaDon> listHD;
    private Vector<String> vcMaKH = new Vector<>(), vcTenKH = new Vector<>(),
            vcTenDV = new Vector<>(), vcSoLuong = new Vector<>();
    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        initComponents();
        readFileKH();
        viewTableKH();
        readFileDV();
        viewTableDV();
        readFileHD();
        phanTach();
        viewTableHD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tenKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        diaChiKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loaiKH = new javax.swing.JComboBox<>();
        themKH = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDV = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tenDV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        giaCuocDV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        donViTinh = new javax.swing.JTextField();
        themDV = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHD = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        maKH2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        maDV2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        soLuong = new javax.swing.JTextField();
        themHD = new javax.swing.JButton();
        xacNhanSP = new javax.swing.JButton();
        sapXep = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        lamMoi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTK = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jTableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "Ho ten", "Dia chi", "Loai"
            }
        ));
        jScrollPane1.setViewportView(jTableKH);

        jLabel1.setText("Ten KH:");

        jLabel2.setText("Dia chi KH:");

        jLabel3.setText("Loai KH: ");

        loaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca nhan", "Dai dien don vi hanh chinh", "Dai dien don vi kinh doanh" }));

        themKH.setText("Them");
        themKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenKH)
                            .addComponent(diaChiKH)
                            .addComponent(loaiKH, 0, 234, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themKH)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(diaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("Khach hang", jToolBar1);

        jToolBar2.setRollover(true);

        jTableDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma ", "Ten", "Gia cuoc", "Don vi tinh"
            }
        ));
        jScrollPane2.setViewportView(jTableDV);

        jLabel4.setText("Ten DV:");

        jLabel5.setText("Gia cuoc:");

        jLabel6.setText("Don vi tinh:");

        themDV.setText("Them");
        themDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenDV, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(giaCuocDV)
                            .addComponent(donViTinh)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themDV)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(giaCuocDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(donViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(themDV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel2);

        jTabbedPane1.addTab("Dich vu", jToolBar2);

        jToolBar3.setRollover(true);

        jTableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma KH", "Ten KH", "Ten DV", "Thang su dung"
            }
        ));
        jScrollPane3.setViewportView(jTableHD);

        jLabel7.setText("Ma/ten KH:");

        jLabel8.setText("Ma/ten DV:");

        jLabel9.setText("Thang su dung:");

        soLuong.setText("0");

        themHD.setText("them");
        themHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themHDActionPerformed(evt);
            }
        });

        xacNhanSP.setText("Xac nhan");
        xacNhanSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhanSPActionPerformed(evt);
            }
        });

        sapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ho ten khach hang", "So luong su dung" }));

        jLabel10.setText("Sap xep theo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maKH2)
                            .addComponent(maDV2)
                            .addComponent(soLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themHD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xacNhanSP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(maKH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(maDV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themHD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xacNhanSP)
                    .addComponent(sapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel3);

        jTabbedPane1.addTab("Hoa don", jToolBar3);

        jToolBar4.setRollover(true);

        lamMoi.setText("Lam moi");
        lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiActionPerformed(evt);
            }
        });

        jTableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma KH", "Ten KH", "Dia chi", "Loai KH", "Tong tien"
            }
        ));
        jScrollPane4.setViewportView(jTableTK);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(lamMoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar4.add(jPanel4);

        jTabbedPane1.addTab("Thong ke", jToolBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themKHActionPerformed
        // TODO add your handling code here:
        themKH();
    }//GEN-LAST:event_themKHActionPerformed

    private void themDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themDVActionPerformed
        // TODO add your handling code here:
        themDV();
    }//GEN-LAST:event_themDVActionPerformed

    private void themHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themHDActionPerformed
        // TODO add your handling code here:
        themHD();
    }//GEN-LAST:event_themHDActionPerformed

    private void xacNhanSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacNhanSPActionPerformed
        // TODO add your handling code here:
        if(sapXep.getSelectedItem().toString().compareTo("Ho ten khach hang") == 0){
            ThaoTacHD.sxTheoTen(vcMaKH, vcTenKH, vcTenDV, vcSoLuong);
            viewTableHD();
        }
        else{
            ThaoTacHD.sxTheoSL(vcMaKH, vcTenKH, vcTenDV, vcSoLuong);
            viewTableHD();
        }
    }//GEN-LAST:event_xacNhanSPActionPerformed

    private void lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamMoiActionPerformed
        // TODO add your handling code here:
        thongKe();
    }//GEN-LAST:event_lamMoiActionPerformed
    
    //them khach hang moi
    private void themKH(){
        try {
            if(!listKH.isEmpty()) KhachHang.setStMa(listKH.get(listKH.size()-1).getMa()+1);
            
            KhachHang kh = new KhachHang(tenKH.getText(), diaChiKH.getText(), 
                    loaiKH.getSelectedItem().toString());
            
            listKH.add(kh);
            ThaoTacKH.writeFile(listKH);
            viewTableKH();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    //doc danh sach dich vu
    private void readFileDV(){
        listDV = ThaoTacDV.readFile();
    }
    //doc danh sach khach hang
    private void readFileKH(){
        listKH = ThaoTacKH.readFile();
    }
    
    //hien thi bang khach hang
    private void viewTableKH(){
        DefaultTableModel model = (DefaultTableModel)jTableKH.getModel();
        
        model.setRowCount(0);
        
        for(int i = 0; i < listKH.size(); i++){
            model.addRow(new Object[]{listKH.get(i).getMa()+"", listKH.get(i).getTen(),
            listKH.get(i).getDiaChi(), listKH.get(i).getLoai()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diaChiKH;
    private javax.swing.JTextField donViTinh;
    private javax.swing.JTextField giaCuocDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDV;
    private javax.swing.JTable jTableHD;
    private javax.swing.JTable jTableKH;
    private javax.swing.JTable jTableTK;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JButton lamMoi;
    private javax.swing.JComboBox<String> loaiKH;
    private javax.swing.JTextField maDV2;
    private javax.swing.JTextField maKH2;
    private javax.swing.JComboBox<String> sapXep;
    private javax.swing.JTextField soLuong;
    private javax.swing.JTextField tenDV;
    private javax.swing.JTextField tenKH;
    private javax.swing.JButton themDV;
    private javax.swing.JButton themHD;
    private javax.swing.JButton themKH;
    private javax.swing.JButton xacNhanSP;
    // End of variables declaration//GEN-END:variables

    //them mot dich vu moi
    private void themDV() {
        try {
            DichVu dv = ThaoTacDV.tim(listDV, tenDV.getText());
            if(dv != null){
                dv.sua(Double.parseDouble(giaCuocDV.getText()), donViTinh.getText());
            }
            else{
                if(!listDV.isEmpty()) DichVu.setStMa(listDV.get(listDV.size()-1).getMa()+1);
                
                dv = new DichVu(tenDV.getText(), Double.parseDouble(giaCuocDV.getText()), 
                        donViTinh.getText());
                listDV.add(dv);
                
            }
            ThaoTacDV.writeFile(listDV);
            viewTableDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    //hien thi danh sach dich vu
    private void viewTableDV() {
        DefaultTableModel model = (DefaultTableModel)jTableDV.getModel();
        
        model.setRowCount(0);
        
        for(int i = 0; i < listDV.size(); i++){
            model.addRow(new Object[]{listDV.get(i).getMa()+"",listDV.get(i).getTen(),
            listDV.get(i).getGiaCuoc()+"",listDV.get(i).getDonViTinh()});
        }
    }

    //them hoac sua hoa don
    private void themHD() {
        KhachHang kh = ThaoTacKH.tim(listKH, maKH2.getText());
        DichVu dv = ThaoTacDV.tim(listDV, maDV2.getText());
        if(dv != null && kh != null){
            HoaDon hd = ThaoTacHD.tim(listHD, kh);
            if(hd != null){
                try {
                    hd.them(dv, Integer.parseInt(soLuong.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            }
            else{
                try {
                    hd = new HoaDon(kh, dv, Integer.parseInt(soLuong.getText()));
                    listHD.add(hd);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            }
            ThaoTacHD.writeFile(listHD);
            phanTach();
            viewTableHD();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "khong tim khach hang hoac dich vu sai");
        }
        
    }
    
    //doc danh sach hoa don
    private void readFileHD(){
        listHD = ThaoTacHD.readFile();
    }
    //lay thong tin cho bang hoa don
    private void phanTach(){
        ThaoTacHD.phanTach(listHD, vcMaKH, vcTenKH, vcTenDV, vcSoLuong);
    }
    
    //hien danh sach hoa don
    private void viewTableHD(){
        DefaultTableModel model = (DefaultTableModel)jTableHD.getModel();
        
        model.setRowCount(0);
        
        for(int i = 0; i < vcMaKH.size(); i++){
            model.addRow(new Object[]{vcMaKH.get(i), vcTenKH.get(i), vcTenDV.get(i),
            vcSoLuong.get(i)});
        }
    }

    private void thongKe() {
        DefaultTableModel model = (DefaultTableModel)jTableTK.getModel();
        
        model.setRowCount(0);
        double sum = 0;
        
        for(int i = 0; i < listHD.size(); i++){
            sum = 0;
            List<DichVu> dvs = listHD.get(i).getListDV();
            List<Integer> list = listHD.get(i).getListsSL();
            
            for(int j = 0; j < dvs.size(); j++){
                sum += dvs.get(j).getGiaCuoc()*list.get(j);
            }
            
            model.addRow(new Object[]{listHD.get(i).getKh().getMa(), listHD.get(i).getKh().getTen(),
            listHD.get(i).getKh().getDiaChi(), listHD.get(i).getKh().getLoai(), sum+""});
        }
    }
}
