/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ThaoTacNV;
import controller.ThaoTacPB;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import model.PhongBan;

/**
 *
 * @author User
 */
public class ViewHome extends javax.swing.JFrame {

    private List<NhanVien> listNV;
    private List<PhongBan> listPB;

    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        initComponents();
        readListNV();
        readListPB();
        viewTableNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNV = new javax.swing.JTable();
        themNhanVien = new javax.swing.JButton();
        boNhanVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jTableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "Ho ten", "Dia chi", "So dien thoai", "Bac luong"
            }
        ));
        jScrollPane1.setViewportView(jTableNV);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("Nhan vien", jToolBar1);

        themNhanVien.setText("Them moi");
        themNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNhanVienActionPerformed(evt);
            }
        });

        boNhanVien.setText("Roi di");
        boNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themNhanVien)
                .addGap(33, 33, 33)
                .addComponent(boNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boNhanVien)
                    .addComponent(themNhanVien))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNhanVienActionPerformed
        // TODO add your handling code here:
        new NhanVienMoi(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_themNhanVienActionPerformed

    private void boNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boNhanVienActionPerformed
        // TODO add your handling code here:
        new NghiViec(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_boNhanVienActionPerformed

    public void themNV(String ten, String diaChia, String std, String bacLuong,
            String maPhong) {
        if (ThaoTacNV.kt(listNV, ten, std) == -1) {
            PhongBan ban = ThaoTacPB.timPB(listPB, maPhong);
            if (ban != null) {
                ThaoTacNV.themNV(listNV, ten, diaChia, std, bacLuong, ban);
                viewTableNV();
                ThaoTacNV.ghiFile(listNV);
            } else {
                JOptionPane.showMessageDialog(rootPane, "phong ban khong ton tai");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nhan vien da co");
        }

    }

    private void viewTableNV() {

        DefaultTableModel model = (DefaultTableModel) jTableNV.getModel();

        model.setRowCount(0);

        Iterator<NhanVien> iterator = listNV.iterator();

        while (iterator.hasNext()) {
            NhanVien temp = iterator.next();

            model.addRow(new Object[]{"" + temp.getMa(), temp.getTen(), temp.getDiaChi(),
                temp.getSdt(), "" + temp.getBacLuong()});
        }
    }

    private void readListNV() {
        listNV = ThaoTacNV.docFile();
    }
    private void readListPB(){
        listPB = ThaoTacPB.docFile();
    }
    
    public void loaiNV(String ma){
        if(ThaoTacNV.boNV(listNV, ma)){
            viewTableNV();
            JOptionPane.showMessageDialog(rootPane, "da xoa nhan vien");
        }else JOptionPane.showMessageDialog(rootPane, "nhan vien khong ton tai");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boNhanVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableNV;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton themNhanVien;
    // End of variables declaration//GEN-END:variables
}
