/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ThaoTacDA;
import controller.ThaoTacNV;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DuAn;
import model.NhanVien;

/**
 *
 * @author ADMIN
 */
public class ViewHome extends javax.swing.JFrame {
    private List<DuAn> listDA;
    private List<NhanVien> listNV;
    private Vector<String> vcTenNV = new Vector<>(), vcTenDA = new Vector<>(),
            vcViTri = new Vector<>(), vcNgayTG = new Vector<>();
    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        initComponents();
        readListDA();
        viewTableDA();
        readListNV();
        viewTableNV();
        phanTach();
        viewTablePhanCong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDA = new javax.swing.JTable();
        xoaDA = new javax.swing.JButton();
        themDA = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNV = new javax.swing.JTable();
        XoaNV = new javax.swing.JButton();
        themNV = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePhanCong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        chonSX = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        maNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maDA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        viTri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ngayThaGia = new javax.swing.JTextField();
        boDA = new javax.swing.JButton();
        nhanDA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jTableDA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "Ten", "Kieu", "Tong kinh phi"
            }
        ));
        jScrollPane1.setViewportView(jTableDA);

        xoaDA.setText("Xoa");
        xoaDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaDAActionPerformed(evt);
            }
        });

        themDA.setText("Them");
        themDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(themDA)
                        .addGap(18, 18, 18)
                        .addComponent(xoaDA))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoaDA)
                    .addComponent(themDA))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("Du An", jToolBar1);

        jToolBar2.setRollover(true);

        jTableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma ", "Ten", "Dia chi", "Chuyen mon"
            }
        ));
        jScrollPane2.setViewportView(jTableNV);

        XoaNV.setText("Xoa");
        XoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaNVActionPerformed(evt);
            }
        });

        themNV.setText("Them");
        themNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themNV)
                .addGap(36, 36, 36)
                .addComponent(XoaNV)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themNV)
                    .addComponent(XoaNV))
                .addGap(45, 45, 45))
        );

        jToolBar2.add(jPanel2);

        jTabbedPane1.addTab("Nhan vien", jToolBar2);

        jToolBar3.setRollover(true);

        jTablePhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma nhan vien", "Ten du an", "Vi tri", "ngay tham gia"
            }
        ));
        jScrollPane3.setViewportView(jTablePhanCong);

        jLabel1.setText("Sap xep theo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ten nhan vien", "So ngay tham gia" }));

        chonSX.setText("Xac nhan");
        chonSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonSXActionPerformed(evt);
            }
        });

        jLabel2.setText("Ten/ma nhan vien:");

        jLabel3.setText("Ten/ma du an:");

        jLabel4.setText("Vi tri:");

        jLabel5.setText("ngay tham gia:");

        boDA.setText("Xoa");
        boDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boDAActionPerformed(evt);
            }
        });

        nhanDA.setText("Them");
        nhanDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nhanDA, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boDA))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maDA)
                            .addComponent(maNV, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(viTri, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ngayThaGia, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chonSX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(maDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(viTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ngayThaGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boDA)
                            .addComponent(nhanDA))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chonSX))
                .addContainerGap())
        );

        jToolBar3.add(jPanel3);

        jTabbedPane1.addTab("Phan cong", jToolBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themDAActionPerformed
        // TODO add your handling code here:
        new DAMoi(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_themDAActionPerformed

    private void xoaDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaDAActionPerformed
        // TODO add your handling code here:
        new XoaDA(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_xoaDAActionPerformed

    private void themNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNVActionPerformed
        // TODO add your handling code here:
        new NhanVienMoi(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_themNVActionPerformed

    private void XoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaNVActionPerformed
        // TODO add your handling code here:
        new XoaNV(this, rootPaneCheckingEnabled).setVisible(true);
        
    }//GEN-LAST:event_XoaNVActionPerformed

    private void boDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boDAActionPerformed
        // TODO add your handling code here:
        thoiDA();
    }//GEN-LAST:event_boDAActionPerformed

    private void nhanDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanDAActionPerformed
        // TODO add your handling code here:
        NhanVien nv = ThaoTacNV.timNV(listNV, maNV.getText());
        DuAn da = ThaoTacDA.tim(listDA, maDA.getText());
        if(nv != null && da != null){
            Pattern pattern = Pattern.compile("\\w+");
            Matcher matcher = pattern.matcher(viTri.getText());
            if(matcher.find() && ngayThaGia.getText().matches("\\d+")){
                if(ThaoTacNV.themDA(nv, da, viTri.getText(), Integer.parseInt(ngayThaGia.getText()))){
                    ThaoTacNV.ghiFile(listNV);
                    phanTach();
                    viewTablePhanCong();
                }
                else JOptionPane.showMessageDialog(rootPane, "nhan vien da tham gia du an");
            }
            else JOptionPane.showMessageDialog(rootPane, "thong tin nhap khong hop le");
        }
        else JOptionPane.showMessageDialog(rootPane, "khong tim thay nhan vien hoac du an");
    }//GEN-LAST:event_nhanDAActionPerformed

    private void chonSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonSXActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().compareTo("Ten nhan vien") == 0){
            ThaoTacNV.sapXepTheoTen(vcTenNV, vcTenDA, vcViTri, vcNgayTG);
            viewTablePhanCong();
        }else{
            ThaoTacNV.sapXepTheoNgay(vcTenNV, vcTenDA, vcViTri, vcNgayTG);
            viewTablePhanCong();
        }
    }//GEN-LAST:event_chonSXActionPerformed
    
    //them du an moi
    public void themDA(String ten, String kieu, String tongKP){
        DuAn da = ThaoTacDA.tim(listDA, ten);
        if(da == null) ThaoTacDA.them(listDA, ten, kieu, tongKP);
        else {
            if(JOptionPane.showConfirmDialog(rootPane, "sua thong tin du an", "Thong bao", 2) == 0){
                ThaoTacDA.sua(da, kieu, tongKP);
            }
            
        }
        ThaoTacDA.ghiFile(listDA);
        viewTableDA();
    }
    
    //xoa mot du an
    public void xoaDA(String ma){
        if(!ThaoTacDA.xoa(listDA, listNV, ma)) 
            JOptionPane.showMessageDialog(rootPane, "du an khong ton tai");
        ThaoTacDA.ghiFile(listDA);
        viewTableDA();
        phanTach();
        viewTablePhanCong();
    }
    
    //them mot nhan vien
    public void themNV(String ten, String diaChi, String chuyenMon){
        ThaoTacNV.themNV(listNV, ten, diaChi, chuyenMon);
        ThaoTacNV.ghiFile(listNV);
        viewTableNV();
        phanTach();
        viewTablePhanCong();
    }
    
    //xoa mot nhan vien
    public void xoaNV(String ma){
        NhanVien nv = ThaoTacNV.timNV(listNV, ma);
        
        if(nv != null){
            listNV.remove(nv);
            ThaoTacNV.ghiFile(listNV);
            viewTableNV();
            phanTach();
            viewTablePhanCong();
        }else JOptionPane.showMessageDialog(rootPane, "nhan vien khong ton tai");
    }
    
    //mot nhan vien thoi du an
    public void thoiDA(){
        DuAn da = ThaoTacDA.tim(listDA, maDA.getText());
        
        if(da != null){
            if(!ThaoTacNV.xoaDA(listNV, maNV.getText(), maDA.getText())) 
                JOptionPane.showMessageDialog(rootPane, "bo du an that bai do thong tin sai");
            else{
                ThaoTacNV.ghiFile(listNV);
                phanTach();
                viewTablePhanCong();
            }
            
        }
    }
    
    //tach thong tin nhan vien cho bang phan cong
    private void phanTach(){
        ThaoTacNV.phanTach(listNV, vcTenNV, vcTenDA, vcViTri, vcNgayTG);
    }
    
    //hien thi bang phan cong
    private void viewTablePhanCong(){
        DefaultTableModel model = (DefaultTableModel)jTablePhanCong.getModel();
        
        model.setRowCount(0);
        
        for(int i = 0; i < vcTenNV.size(); i++){
            model.addRow(new Object[]{vcTenNV.get(i), vcTenDA.get(i), vcViTri.get(i),
                vcNgayTG.get(i)});
        }
    }
    
    private void readListDA(){
        listDA = ThaoTacDA.docFile();
    }
    
    private void readListNV(){
        listNV = ThaoTacNV.docFile();
    }
    
    private void viewTableDA(){
        DefaultTableModel model = (DefaultTableModel)jTableDA.getModel();
        
        model.setRowCount(0);
        
        for(int i = 0; i < listDA.size(); i++){
            model.addRow(new Object[]{""+listDA.get(i).getMa(), listDA.get(i).getTenDA(),
            listDA.get(i).getKieuDA(), listDA.get(i).getTong()});
        }
    }
    
    private void viewTableNV(){
        DefaultTableModel model = (DefaultTableModel)jTableNV.getModel();
        
        model.setRowCount(0);
        
        for(int i = 0; i < listNV.size(); i++){
            model.addRow(new Object[]{""+listNV.get(i).getMa(), listNV.get(i).getHoTen(),
            listNV.get(i).getDiaChi(), listNV.get(i).getChuyenMon()});
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XoaNV;
    private javax.swing.JButton boDA;
    private javax.swing.JButton chonSX;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDA;
    private javax.swing.JTable jTableNV;
    private javax.swing.JTable jTablePhanCong;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTextField maDA;
    private javax.swing.JTextField maNV;
    private javax.swing.JTextField ngayThaGia;
    private javax.swing.JButton nhanDA;
    private javax.swing.JButton themDA;
    private javax.swing.JButton themNV;
    private javax.swing.JTextField viTri;
    private javax.swing.JButton xoaDA;
    // End of variables declaration//GEN-END:variables
}
